title: Oxford Robotics Graduate Society (ORGS)
logo: orgs.png

>TERM CARD
>- SMASH BROS. Social (April 23rd 2024)
>- Dyson Demo - Prof Rob Deaves demonstrating Dyson 360 Visial Navigation System (June 7th 2024)

theme: jekyll-theme-minimal
